pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"
pin "turmas", preload: true
pin "confirm_modal"
pin "custom/theme_toggle"
pin "alunos_modal"
pin "configuracoes", to: "configuracoes.js"
pin "gerenciar_usuarios", to: "gerenciar_usuarios.js"