import "@hotwired/turbo-rails"
import "controllers"
import "confirm_modal"
import "custom/theme_toggle"
import "alunos_modal"
import "configuracoes"
import "gerenciar_usuarios"
import "gerenciar_alunos_turma"
